### ISSUE TITLE
Support to mutiples depedencies and save folder path.

### ISSUE THREAD

**Issue by jppgmx** [clausnz/github-action-download-maven-artifact#2]
### Actual Situation

This action only download one file, and saved in `tmp/<some random uuid>`.

### What is being asked for?

My request is that this action can support multiple artifacts and that the folder can be customized. For multiples artifacts required i was think in create a JSON file with all the artifacts.

### Why this request?

I have a library what needs retrieve a maven artifact, see below:
```yaml
- name: Retrieve Markdown Doclet from Maven
      uses: clausnz/github-action-download-maven-artifact@0.0.4
      with:
        url: 'https://repo1.maven.org'
        repository: 'maven2'
        groupId: 'ch.raffael.markdown-doclet'
        artifactId: 'markdown-doclet'
        version: '1.4'
        extension: 'jar'
```
I was looking your `pom` file and i find some other depedencies that artifact. [Pom File](https://repo1.maven.org/maven2/ch/raffael/markdown-doclet/markdown-doclet/1.4/markdown-doclet-1.4.pom). If these depedencies aren't downloaded, this `jar` file will give error.

### What can be do to resolve it?

My idea is:

1. Download the Jar.
2. Find and get the `pom` file.
3. Access the `depedencies` section and recursivelly get the artifacts.
4. Zip all in a `temp` folder and save in a specific folder declared in actions.
5. Done.
